### ISSUE TITLE
How to import to edge and use this jar

### ISSUE THREAD

**Issue by Tamil2k** [DinoChiesa/ApigeeEdge-Java-Validate-JSON-Schema#1]
Hi Dino,

It would be helpful if you provide further information.

Do i need to  import only edge-custom-json-schema-validator-1.0.1.jar or should i import all dependent jar .

Should i compile the code in eclipse and build the archive before importing it ?

I imported the code and ran it . It throws error.

error |   | Found class com.github.fge.jsonschema.main.JsonSchema, but interface was expected
-- | -- | --
  | java.lang.IncompatibleClassChangeError
  | fault
  | PROXY_REQ_FLOW
  | ErrorPoint

**Comment by DinoChiesa** [comment]
You need to include all the dependent jars to get this to work.  There are lots of them!  Check the example bundle directory for the full list.
